# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


def default_pods
    	pod 'Alamofire'
	pod 'lottie-ios'
        pod 'RxSwift'
	pod 'RxCocoa'
end

  # Pods for WeatherApp
	default_pods
	
	

  target 'WeatherAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeatherAppUITests' do
    # Pods for testing
  end

target 'WeatherApp Prod' do
    default_pods
end

target 'WeatherApp Stag' do
    default_pods
end

end
